import { ReactNode } from 'react'
import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { tv } from 'tailwind-variants'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const rootLayoutStyles = tv({ base: 'min-h-dvh flex flex-col' })

const RootLayout = ({
  children,
  header,
  footer,
  navbar,
}: Readonly<{
  children: ReactNode
  header: ReactNode
  footer: ReactNode
  navbar: ReactNode
}>) => {
  return (
    <html lang="ja">
      <body className={inter.className}>
        {header}
        <div className={rootLayoutStyles()}>{children}</div>
        {footer}
        {navbar}
      </body>
    </html>
  )
}

export default RootLayout
