import { Product } from '@/types/Product'
import { v4 as uuidv4 } from 'uuid'

export const products = [
  {
    id: uuidv4(),
    price: 500,
    images: [
      'kids-socks.jpeg',
      'nike.jpeg',
      'mens-cloth.jpeg',
      'nike.jpeg',
      'kids-socks.jpeg',
      'kids-socks.jpeg',
      'nike.jpeg',
      'mens-cloth.jpeg',
      'nike.jpeg',
      'kids-socks.jpeg',
      'kids-socks.jpeg',
      'nike.jpeg',
      'mens-cloth.jpeg',
      'nike.jpeg',
      'kids-socks.jpeg',
    ],
    name: '子供用靴下',
    description: '商品説明です。',
    category: 'ベビー・キッズ',
    size: '11cm',
    color: 'ピンク',
    status: '目立った傷や汚れなし',
    shippingCharges: '送料込み(出品者負担)',
    region: '沖縄県',
    shippingDate: '2〜3日で発送',
    isSoldOut: false,
  },
  {
    id: uuidv4(),
    price: 99999999,
    images: ['mens-cloth.jpeg'],
    name: '白紺ボーダーニット',
    description: '商品説明です。',
    category: 'メンズ',
    size: 'M',
    color: '紺',
    status: '目立った傷や汚れなし',
    shippingCharges: '送料込み(出品者負担)',
    region: '埼玉県',
    shippingDate: '2〜3日で発送',
    isSoldOut: true,
  },
  {
    id: uuidv4(),
    price: 100000,
    images: ['nike.jpeg'],
    name: 'NIKE スニーカー',
    description: '商品説明です。',
    category: 'メンズ',
    size: '26.5cm',
    color: '白',
    status: '未使用に近い',
    shippingCharges: '着払い(購入者負担)',
    region: '北海道',
    shippingDate: '1〜2日で発送',
    isSoldOut: false,
  },
] as const satisfies Product[]
